# Generated by Django 4.2.11 on 2026-03-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0003_channelinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
